name: Continuous Delivery
on:
  push:
    branches:
      - main
jobs:
  Deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Simulando
        uses: actions/upload-artifact@v4
        with:
          name: projetozip.zip
          path: |
            '**.py'
     
  Deploy:
    runs-on: ubuntu-latest
    needs: Deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projetozip.zip

      - name: Display structure of downloaded files
        run: ls -R

      
